// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1FnmBaOpuJhAXL-2UI6yuPKo7vaPMD0Y',
    appId: '1:1019906540743:web:f6bb696ab152b53307eae2',
    messagingSenderId: '1019906540743',
    projectId: 'mess-messenger-77af2',
    authDomain: 'mess-messenger-77af2.firebaseapp.com',
    storageBucket: 'mess-messenger-77af2.firebasestorage.app',
    measurementId: 'G-X8GFZVCYSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC603Krbs6D3zScQr3b1NUqFkCx3lbiew',
    appId: '1:1019906540743:android:40b1680986c457c507eae2',
    messagingSenderId: '1019906540743',
    projectId: 'mess-messenger-77af2',
    storageBucket: 'mess-messenger-77af2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRTRbWSO3Meh5W3T4S34ms9UvFsLQrjVs',
    appId: '1:1019906540743:ios:f4eb500bd117be5807eae2',
    messagingSenderId: '1019906540743',
    projectId: 'mess-messenger-77af2',
    storageBucket: 'mess-messenger-77af2.firebasestorage.app',
    androidClientId: '1019906540743-mfms1inmgfk20l128eqd1ml30gfff9e6.apps.googleusercontent.com',
    iosClientId: '1019906540743-dp7iqemel490ql3kvjmh0big7o696qcl.apps.googleusercontent.com',
    iosBundleId: 'com.messmessenger.messMessengerApp',
  );

}