// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB27jVd8NKF1HnwBmeZxDmNMfVNfdpyAaQ',
    appId: '1:74270236491:web:d5d9d84cd259bb09bbd2ce',
    messagingSenderId: '74270236491',
    projectId: 'mess-messenger-14491',
    authDomain: 'mess-messenger-14491.firebaseapp.com',
    storageBucket: 'mess-messenger-14491.firebasestorage.app',
    measurementId: 'G-R9JF986DWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz_WaRyGwjjJrVAw6Is4_SUN-LDCrI_MY',
    appId: '1:74270236491:android:fe1cb527fbb5ff95bbd2ce',
    messagingSenderId: '74270236491',
    projectId: 'mess-messenger-14491',
    storageBucket: 'mess-messenger-14491.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVuBXm7DuGhITSqT5wwvVshiurCLYnS-U',
    appId: '1:74270236491:ios:608ec786663c624cbbd2ce',
    messagingSenderId: '74270236491',
    projectId: 'mess-messenger-14491',
    storageBucket: 'mess-messenger-14491.firebasestorage.app',
    androidClientId: '74270236491-hgm53fpbekj4i74i74i6tgloq2k5rj5i.apps.googleusercontent.com',
    iosBundleId: 'com.messmessenger.messMessengerApp',
  );
}
